Filter out storybooks in CoreGui
flipbook-labs/flipbook pull request #220
Opened 2023-08-05 19:40 UTC by vocksel

# Problem
When opening flipbook several warnings appear in the output from it attempting to load Roblox-created storybooks in CoreGui
```
  12:37:42.545  Failed to load storybook CoreGui.RobloxGui.Modules.VoiceChatPrompt.VoiceChatPrompt.storybook. Error: table expected, got nil  -  Edit - useStorybooks:40
  12:37:42.545  Failed to load storybook CoreGui.RobloxGui.Modules.Settings.Settings.storybook. Error: table expected, got nil  -  Edit - useStorybooks:40
  12:37:42.545  Failed to load storybook CoreGui.RobloxGui.Modules.InGameChat.BubbleChat.BubbleChat.storybook. Error: table expected, got nil  -  Edit - useStorybooks:40
  12:37:42.545  Failed to load storybook CoreGui.RobloxGui.Modules.TopBar.TopBar.storybook. Error: table expected, got nil  -  Edit - useStorybooks:40
  12:37:42.545  Failed to load storybook CoreGui.RobloxGui.Modules.ContactList.ContactList.storybook. Error: table expected, got nil  -  Edit - useStorybooks:40
```

# Solution

To fix this, I've updated `isStorybookModule` to return `false` for any storybook in CoreGui

# Checklist

- [x] Ran `./bin/test.sh` locally before merging

2023-08-06 20:34 UTC, passhley requested changes
Overall looks fine to me, just a few changes

2023-08-06 20:34 UTC, passhley commented on src/Story/isStorybookModule.lua
nitpick, but could we move Services to the top of the file?

2023-08-06 20:34 UTC, passhley commented on wally.toml
This is the same as my comment on [219](https://github.com/flipbook-labs/flipbook/pull/219)

2023-08-13 19:45 UTC, vocksel commented on src/Story/isStorybookModule.lua
Usually I follow the order of:
1. Variable to root of project
2. Services
3. Imports
4. Constants
5. Variables/functions/etc.
I'm pretty sure this is consistent across most of the codebase

2023-11-18 19:51 UTC, passhley approved these changes

2023-11-19 00:21 UTC, merged