Use DataModel analysis
flipbook-labs/flipbook pull request #227
Opened 2023-11-25 00:47 UTC by vocksel

# Problem

Describe the problem you are trying to solve

# Solution

Describe the solution you came up with

# Checklist

- [ ] Ran `./bin/test.sh` locally before merging

2023-11-25 21:14 UTC, passhley requested changes
Only 2 things I left comments for, however the first one happens across multiple files

2023-11-25 21:14 UTC, passhley commented on src/Components/ComponentTree/Component/Directory.lua
Few things:
1. We should be calling it `ReactSpring` now since that aligns more with the package itself and what it's used for.
2. Why are we casting useSpring to any here?

2023-11-25 21:14 UTC, passhley commented on src/Plugin/PluginContext.lua
It's also usually a good idea to set up context something like
```lua
local React = require(flipbook.Packages.React)

export type ContextValue = {
    plugin: Plugin,
}

local PluginContext = React.createContext({} :: ContextValue}
```

This usually adds autocomplete for context when you `useContext` it

2023-11-27 02:15 UTC, vocksel commented on src/Components/ComponentTree/Component/Directory.lua
1. Simple enough rename. I could do that in this PR or make a new one. Up to you
2. I didn't look at it hard enough. From what I can tell all our animations are working properly, but useSpring was giving analysis errors. So I casted to `any` to punt this issue down the road

2023-11-30 20:47 UTC, passhley commented on src/Components/ComponentTree/Component/Directory.lua
We can leave it for another PR :)

2023-12-01 01:25 UTC, merged